### ISSUE TITLE
[Feature Request] Support Typescript

### ISSUE THREAD

**Issue by BlackYuzia** [SCDerox/simple-discord-webhooks#4]
Hi there.
Thx for cool tool for webhooks :3

**Could you add some support for typescript?**
I also try create a PR in free time.

Something like this:
```ts
interface IDiscordWebhook {
  send(content?: string, embeds?: object[], allowedMentions?: object, tts?: boolean, components?: object[]): Promise<IDiscordMessage>;
  delete(): Promise<any>;
  edit(content: string, embeds?: object[], allowedMentions?: object, components?: object[]): Promise<IDiscordMessage>;
  fetchMessage(id): Promise<IDiscordMessage>;
  resolveMessageID(id): IDiscordMessage;
}

interface IDiscordMessage {
  id;
  type;
  content;
  author;
  channel_id;
  embeds;
  tts;
  timestamp;
  webhook_id;
  messageData: object;
  webhookUrl: URL;
  delete(): Promise<any>;
  edit(content: string, embeds?: object[], allowedMentions?: object, components?: object[]): Promise<IDiscordMessage>;
}
```

**Comment by SCDerox** [comment]
Thanks for your suggestion. I haven't worked a lot with Typescript yet, that's why this package is in plain JS. Once I am more comfortable with using typescript, I've planed to rewrite this package fully.
Until then, feel free to open a PR ^^

**Comment by SCDerox** [comment]
I've added basic typescript-support (based on [discord-api-types](https://discord-api-types.dev/)). Feel free to comment if you have any questions/issues or suggestions.
