### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by BlackYuzia** [SCDerox/simple-discord-webhooks#5]
Hi there.

I have a question about:
https://github.com/SCDerox/simple-discord-webhooks/blob/main/Webhook.js#L41
https://github.com/SCDerox/simple-discord-webhooks/blob/main/Webhook.js#L58
https://github.com/SCDerox/simple-discord-webhooks/blob/main/Webhook.js#L67
https://github.com/SCDerox/simple-discord-webhooks/blob/main/Webhook.js#L78

For example, in my case I could get a rate limit
```json
{
  "global": false,
  "message": "You are being rate limited.",
  "retry_after": 550
}
```
But, what a trouble, you return a string like this:
![image](https://user-images.githubusercontent.com/25010528/157151733-26c9f6e7-d6d3-42c0-85fb-4863d88e765f.png)

I think we have a few solutions:
1. Create own Error class and return error with:
```js
throw new OurError({message: "...", body: {...}, webhookURL: this.url}) // body of response from discord api as object or json string
```
2. Just return res.body as message without any else text (so we get just json)

**Comment by SCDerox** [comment]
I completely agree with you, this is less than optimal. I have added the "bug" label, as this makes it difficult to efficiently parse the error you get. I personally like your first approach more, and will implement it, when I find time (as always you can also create a PR).
