### ISSUE TITLE
Support for getting webhook information.

### ISSUE THREAD

**Issue by itzTheMeow** [SCDerox/simple-discord-webhooks#6]
Is there a way to get the webhook information gotten by making a GET request to the webhook URL?
![image](https://user-images.githubusercontent.com/50887230/190949123-88cd1fbe-40e6-4dab-96f5-0652832a3957.png)

It'd also allow for checking if a webhook URL/token is valid using these two
![image](https://user-images.githubusercontent.com/50887230/190949160-e269943a-37da-4a9e-ac3e-d177a214d362.png)
![image](https://user-images.githubusercontent.com/50887230/190949163-ef245367-e0b0-44f2-a785-2fc2f0a2deb5.png)

**Comment by SCDerox** [comment]
Yes, this is possible via this [API Call](https://discord.com/developers/docs/resources/webhook#get-webhook-with-token). Feel free to raise a PR if you want to implement it. If not, please send a mesage and I'll look into it.

**Comment by itzTheMeow** [comment]
:)

**Comment by SCDerox** [comment]
Closed in #7
